version: "3"

### Creates a named network with the default bridge driver
# The network can be shared between restheart and other containers
# See: https://docs.docker.com/engine/userguide/networking/dockernetworks/
# See: https://docs.docker.com/engine/reference/commandline/network_create/
networks:
   restheart-backend:

services:
    restheart:
        build:
            context: ./docker
            dockerfile: Dockerfile-microd
        container_name: restheart
        networks:
            - restheart-backend
        ports:
            - "8080:8080"
            - "4000:4000"
        volumes:
            - ./etc/:/opt/restheart/etc:ro
            - ./target/restheart-plugin-skeleton.jar:/opt/restheart/plugins/restheart-plugin-skeleton.jar:ro
            - ./target/lib/.:/opt/restheart/lib:ro

    # this small container is here just to keep docker-compose logging when restheart container restarts
    dummy:
        container_name: dummy
        image: alpine:3.7
        command: tail -f /dev/null
        init: true